name: flounaelza
description: "Flounaelza App"
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10
  intl: 0.19.0
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  hydrated_bloc: 9.1.5
  path_provider: 2.1.4
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  go_router: 14.2.7
  google_fonts: 6.2.1
  dio: 5.7.0
  flutter_dotenv: 5.1.0
  mmkv: 1.3.9
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5
  cached_network_image: 3.4.1
  flutter_native_splash: 2.4.1
  flutter_localization: 0.2.2
  webview_flutter: ^4.10.0
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  package_info_plus: ^8.1.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: 2.4.9
  freezed: 2.5.2
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
